version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prode-backend
    ports:
      - "5000:5000"
    volumes:
      - prode-db:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prode-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  prode-db:
    driver: local
